# Generated by Django 2.0.1 on 2018-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_self',
            field=models.ForeignKey(default=0, on_delete='SET_NULL', to='monitor.Template'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceitems',
            name='data_type',
            field=models.CharField(choices=[('int', 'int'), ('float', 'float'), ('str', 'string')], default=1, max_length=32, verbose_name='指标数据类型'),
        ),
    ]
