# Generated by Django 2.0.1 on 2018-01-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20180117_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.SmallIntegerField(choices=[(0, '报警事件'), (1, '维护事件')], default=0)),
                ('log', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete='CASCADE', to='monitor.Host')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='monitor.Trigger')),
            ],
        ),
        migrations.AlterField(
            model_name='template',
            name='template_self',
            field=models.ForeignKey(blank=True, on_delete='SET_NULL', to='monitor.Template', verbose_name='关联模板列表'),
        ),
    ]
