# Generated by Django 2.0.1 on 2018-01-27 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20180128_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionoperation',
            name='action_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('script', 'script')], default='email', max_length=64, verbose_name='动作类型'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Host'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Service', verbose_name='关联服务'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='service_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.ServiceItems', verbose_name='关联服务指标'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Trigger', verbose_name='所属触发器'),
        ),
    ]
